### PR TITLE
Added Virtaal to the list of recommended translation editors.

### PR DESCRIPTION
**Pull request by gunchleoc**

### CODE REVIEW

**Comment by vorot93** [comment]
I think we should do away with this kind of list completely and let the user decide which editor to use.

**Comment by gunchleoc** [comment]
I still think it's a good idea to have it in for people who are new to translating, before that start hacking in Notepad or something, because they don't know that proper tools exist.

**Comment by vassilis-papanikolaou** [comment]
This is a 'suggestion', ultimately the user is free to decide which editor to use.

**Comment by dbear496** [comment]
I propose that we remove the list and instead provide a link to https://www.gnu.org/software/trans-coord/manual/web-trans/html_node/PO-Editors.html which is a list of PO editors recommended by the GNU project.

**Comment by dbear496** [comment]
This has been superseded by PR #94.

**Pull request closed without merging**
